name: 'Create timeline animation'
description: 'Create animation from your github contributions timeline'
author: 'Zxilly'
inputs:
  token:
    description: 'Github token'
    required: true
    default: ${{ github.token }}
  name:
    description: 'Name displayed in the animation, by default it is the username of the token'
    required: false
  output:
    description: 'Output file name'
    required: false
    default: 'animation.webp'
  type:
    description: 'Output file type, can be webp or gif'
    required: false
    default: 'webp'
runs:
  using: 'composite'
  steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v4'
      with:
        fetch-depth: 0

    - name: 'Install pnpm'
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: 'Install dependencies'
      shell: bash
      run: 'pnpm install -P'

    - name: 'Create animation'
      shell: bash
      run: 'pnpm run create'
      env:
        TOKEN: ${{ inputs.token }}
        NAME: ${{ inputs.name }}
        OUTPUT: ${{ inputs.output }}
        TYPE: ${{ inputs.type }}

