name: Clean outdated image
on:
  workflow_dispatch:

permissions: write-all

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Clean outdated image
        uses: actions/github-script@v9
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const shouldDelete = require('./.github/scripts/should-delete-image.cjs');

            const response = await github.request("GET /user/packages/container/${{ env.PACKAGE_NAME }}/versions",
              { per_page: ${{ env.PER_PAGE }}
            });
            for (const version of response.data) {
                if (shouldDelete(version)) {
                    console.log("delete " + version.id)
                    const deleteResponse = await github.request("DELETE /user/packages/container/${{ env.PACKAGE_NAME }}/versions/" + version.id, { });
                    console.log("status " + deleteResponse.status)
                }
            }
        env:
          OWNER: Zxilly
          PACKAGE_NAME: animatedtimeline
          PER_PAGE: 100
